const project = process.env.SUPABASE_PROJECT;

export const allPhotos = [
  {
    url: `https://${project}.supabase.co/storage/v1/object/public/gallery/glam/photo0.jpeg`,
    alt: 'glam photo 0',
    category: 'glam',
    isShown: true,
    isFeatured: true,
  },
  {
    url: `https://${project}.supabase.co/storage/v1/object/public/gallery/glam/photo1.jpeg`,
    alt: 'glam photo 1',
    category: 'glam',
    isShown: true,
    isFeatured: false,
  },
  {
    url: `https://${project}.supabase.co/storage/v1/object/public/gallery/glam/photo2.jpeg`,
    alt: 'glam photo 2',
    category: 'glam',
    isShown: true,
    isFeatured: false,
  },
  {
    url: `https://${project}.supabase.co/storage/v1/object/public/gallery/glam/photo3.jpeg`,
    alt: 'glam photo 3',
    category: 'glam',
    isShown: true,
    isFeatured: true,
  },
  {
    url: `https://${project}.supabase.co/storage/v1/object/public/gallery/glam/photo4.jpeg`,
    alt: 'glam photo 4',
    category: 'glam',
    isShown: true,
    isFeatured: false,
  },
  {
    url: `https://${project}.supabase.co/storage/v1/object/public/gallery/glam/photo5.jpeg`,
    alt: 'glam photo 5',
    category: 'glam',
    isShown: true,
    isFeatured: false,
  },
  {
    url: `https://${project}.supabase.co/storage/v1/object/public/gallery/glam/photo6.jpeg`,
    alt: 'glam photo 6',
    category: 'glam',
    isShown: true,
    isFeatured: false,
  },
  {
    url: `https://${project}.supabase.co/storage/v1/object/public/gallery/glam/photo7.jpeg`,
    alt: 'glam photo 7',
    category: 'glam',
    isShown: true,
    isFeatured: true,
  },
  {
    url: `https://${project}.supabase.co/storage/v1/object/public/gallery/glam/photo8.jpeg`,
    alt: 'glam photo 8',
    category: 'glam',
    isShown: true,
    isFeatured: true,
  },
  {
    url: `https://${project}.supabase.co/storage/v1/object/public/gallery/glam/photo9.jpeg`,
    alt: 'glam photo 9',
    category: 'glam',
    isShown: true,
    isFeatured: false,
  },
  {
    url: `https://${project}.supabase.co/storage/v1/object/public/gallery/glam/photo10.jpeg`,
    alt: 'glam photo 10',
    category: 'glam',
    isShown: true,
    isFeatured: false,
  },
  {
    url: `https://${project}.supabase.co/storage/v1/object/public/gallery/bridalbridal/photo0.jpeg`,
    alt: 'bridal photo 0',
    category: 'bridal',
    isShown: true,
    isFeatured: true,
  },
  {
    url: `https://${project}.supabase.co/storage/v1/object/public/gallery/bridal/photo1.jpeg`,
    alt: 'bridal photo 1',
    category: 'bridal',
    isShown: true,
    isFeatured: false,
  },
  {
    url: `https://${project}.supabase.co/storage/v1/object/public/gallery/bridal/photo2.jpeg`,
    alt: 'bridal photo 2',
    category: 'bridal',
    isShown: true,
    isFeatured: false,
  },
  {
    url: `https://${project}.supabase.co/storage/v1/object/public/gallery/bridal/photo3.jpeg`,
    alt: 'bridal photo 3',
    category: 'bridal',
    isShown: true,
    isFeatured: false,
  },
  {
    url: `https://${project}.supabase.co/storage/v1/object/public/gallery/bridal/photo4.jpeg`,
    alt: 'bridal photo 4',
    category: 'bridal',
    isShown: true,
    isFeatured: false,
  },
  {
    url: `https://${project}.supabase.co/storage/v1/object/public/gallery/bridal/photo5.jpeg`,
    alt: 'bridal photo 5',
    category: 'bridal',
    isShown: true,
    isFeatured: false,
  },
];
