const project = process.env.NEXT_PUBLIC_SUPABASE_PROJECT;

export const allPhotos = [
  {
    url: `https://${project}.supabase.co/storage/v1/object/public/gallery/photo0.jpeg`,
    alt: "glam photo 0",
    category: "glam",
    isShown: true,
    isFeatured: true,
  },
  {
    url: `https://${project}.supabase.co/storage/v1/object/public/gallery/photo1.jpeg`,
    alt: "glam photo 1",
    category: "glam",
    isShown: true,
    isFeatured: false,
  },
  {
    url: `https://${project}.supabase.co/storage/v1/object/public/gallery/photo2.jpeg`,
    alt: "glam photo 2",
    category: "glam",
    isShown: true,
    isFeatured: false,
  },
  {
    url: `https://${project}.supabase.co/storage/v1/object/public/gallery/photo3.jpeg`,
    alt: "glam photo 3",
    category: "glam",
    isShown: true,
    isFeatured: true,
  },
  {
    url: `https://${project}.supabase.co/storage/v1/object/public/gallery/photo4.jpeg`,
    alt: "glam photo 4",
    category: "glam",
    isShown: true,
    isFeatured: false,
  },
  {
    url: `https://${project}.supabase.co/storage/v1/object/public/gallery/photo5.jpeg`,
    alt: "glam photo 5",
    category: "glam",
    isShown: true,
    isFeatured: false,
  },
  {
    url: `https://${project}.supabase.co/storage/v1/object/public/gallery/photo6.jpeg`,
    alt: "glam photo 6",
    category: "glam",
    isShown: true,
    isFeatured: false,
  },
  {
    url: `https://${project}.supabase.co/storage/v1/object/public/gallery/photo7.jpeg`,
    alt: "glam photo 7",
    category: "glam",
    isShown: true,
    isFeatured: true,
  },
  {
    url: `https://${project}.supabase.co/storage/v1/object/public/gallery/photo8.jpeg`,
    alt: "glam photo 8",
    category: "glam",
    isShown: true,
    isFeatured: true,
  },
  {
    url: `https://${project}.supabase.co/storage/v1/object/public/gallery/photo9.jpeg`,
    alt: "glam photo 9",
    category: "glam",
    isShown: true,
    isFeatured: false,
  },
  {
    url: `https://${project}.supabase.co/storage/v1/object/public/gallery/photo10.jpeg`,
    alt: "glam photo 10",
    category: "glam",
    isShown: true,
    isFeatured: false,
  },
  {
    url: `https://${project}.supabase.co/storage/v1/object/public/gallery/photo11.jpeg`,
    alt: "glam photo 11",
    category: "glam",
    isShown: true,
    isFeatured: false,
  },
  {
    url: `https://${project}.supabase.co/storage/v1/object/public/gallery/photo12.jpeg`,
    alt: "bridal photo 0",
    category: "bridal",
    isShown: true,
    isFeatured: true,
  },
  {
    url: `https://${project}.supabase.co/storage/v1/object/public/gallery/photo13.jpeg`,
    alt: "bridal photo 1",
    category: "bridal",
    isShown: true,
    isFeatured: true,
  },
  {
    url: `https://${project}.supabase.co/storage/v1/object/public/gallery/photo14.jpeg`,
    alt: "bridal photo 2",
    category: "bridal",
    isShown: true,
    isFeatured: true,
  },
  {
    url: `https://${project}.supabase.co/storage/v1/object/public/gallery/photo15.jpeg`,
    alt: "bridal photo 3",
    category: "bridal",
    isShown: true,
    isFeatured: true,
  },
  {
    url: `https://${project}.supabase.co/storage/v1/object/public/gallery/photo16.jpeg`,
    alt: "bridal photo 4",
    category: "bridal",
    isShown: true,
    isFeatured: true,
  },
  {
    url: `https://${project}.supabase.co/storage/v1/object/public/gallery/photo17.jpeg`,
    alt: "bridal photo 5",
    category: "bridal",
    isShown: true,
    isFeatured: true,
  },
];
