const project = process.env.NEXT_PUBLIC_SUPABASE_PROJECT;

export const photoSeed = [
  {
    url: `https://${project}.supabase.co/storage/v1/object/public/portfolio/photo0.jpeg`,
    alt: "glam photo 0",
    category: "glam",
    isShown: true,
    isFeatured: true,
  },
  {
    url: `https://${project}.supabase.co/storage/v1/object/public/portfolio/photo1.jpeg`,
    alt: "glam photo 1",
    category: "glam",
    isShown: true,
    isFeatured: false,
  },
  {
    url: `https://${project}.supabase.co/storage/v1/object/public/portfolio/photo2.jpeg`,
    alt: "glam photo 2",
    category: "glam",
    isShown: true,
    isFeatured: false,
  },
  {
    url: `https://${project}.supabase.co/storage/v1/object/public/portfolio/photo3.jpeg`,
    alt: "glam photo 3",
    category: "glam",
    isShown: true,
    isFeatured: true,
  },
  {
    url: `https://${project}.supabase.co/storage/v1/object/public/portfolio/photo4.jpeg`,
    alt: "glam photo 4",
    category: "glam",
    isShown: true,
    isFeatured: false,
  },
  {
    url: `https://${project}.supabase.co/storage/v1/object/public/portfolio/photo5.jpeg`,
    alt: "glam photo 5",
    category: "glam",
    isShown: true,
    isFeatured: false,
  },
  {
    url: `https://${project}.supabase.co/storage/v1/object/public/portfolio/photo6.jpeg`,
    alt: "glam photo 6",
    category: "glam",
    isShown: true,
    isFeatured: false,
  },
  {
    url: `https://${project}.supabase.co/storage/v1/object/public/portfolio/photo7.jpeg`,
    alt: "glam photo 7",
    category: "glam",
    isShown: true,
    isFeatured: true,
  },
  {
    url: `https://${project}.supabase.co/storage/v1/object/public/portfolio/photo8.jpeg`,
    alt: "glam photo 8",
    category: "glam",
    isShown: true,
    isFeatured: true,
  },
  {
    url: `https://${project}.supabase.co/storage/v1/object/public/portfolio/photo9.jpeg`,
    alt: "glam photo 9",
    category: "glam",
    isShown: true,
    isFeatured: false,
  },
  {
    url: `https://${project}.supabase.co/storage/v1/object/public/portfolio/photo10.jpeg`,
    alt: "glam photo 10",
    category: "glam",
    isShown: true,
    isFeatured: false,
  },
  {
    url: `https://${project}.supabase.co/storage/v1/object/public/portfolio/photo11.jpeg`,
    alt: "glam photo 11",
    category: "glam",
    isShown: true,
    isFeatured: false,
  },
  {
    url: `https://${project}.supabase.co/storage/v1/object/public/portfolio/photo12.jpeg`,
    alt: "bridal photo 0",
    category: "bridal",
    isShown: true,
    isFeatured: true,
  },
  {
    url: `https://${project}.supabase.co/storage/v1/object/public/portfolio/photo13.jpeg`,
    alt: "bridal photo 1",
    category: "bridal",
    isShown: true,
    isFeatured: true,
  },
  {
    url: `https://${project}.supabase.co/storage/v1/object/public/portfolio/photo14.jpeg`,
    alt: "bridal photo 2",
    category: "bridal",
    isShown: true,
    isFeatured: true,
  },
  {
    url: `https://${project}.supabase.co/storage/v1/object/public/portfolio/photo15.jpeg`,
    alt: "bridal photo 3",
    category: "bridal",
    isShown: true,
    isFeatured: true,
  },
  {
    url: `https://${project}.supabase.co/storage/v1/object/public/portfolio/photo16.jpeg`,
    alt: "bridal photo 4",
    category: "bridal",
    isShown: true,
    isFeatured: true,
  },
  {
    url: `https://${project}.supabase.co/storage/v1/object/public/portfolio/photo17.jpeg`,
    alt: "bridal photo 5",
    category: "bridal",
    isShown: true,
    isFeatured: true,
  },
];
